//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DockerAppStarter.Gui.Assets.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DockerAppStarter.Gui.Assets.I18N.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        internal static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at line `{0}`.
        /// </summary>
        internal static string AtLine {
            get {
                return ResourceManager.GetString("AtLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to called by `{0}`.
        /// </summary>
        internal static string CalledBy {
            get {
                return ResourceManager.GetString("CalledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency service `{0}` not found..
        /// </summary>
        internal static string DependencyServiceNotFound {
            get {
                return ResourceManager.GetString("DependencyServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker executable file path is not set..
        /// </summary>
        internal static string DockerExecutableFilePathNotSet {
            get {
                return ResourceManager.GetString("DockerExecutableFilePathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker Service name is not set..
        /// </summary>
        internal static string DockerServiceNameNotSet {
            get {
                return ResourceManager.GetString("DockerServiceNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File `{0}` not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in file `{0}`.
        /// </summary>
        internal static string InFile {
            get {
                return ResourceManager.GetString("InFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of `class` is null..
        /// </summary>
        internal static string InstanceOfClassIsNull {
            get {
                return ResourceManager.GetString("InstanceOfClassIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body of `{0}` should be a `{1}`, instead it&apos;s `{2}`..
        /// </summary>
        internal static string InvalidMethodBody {
            get {
                return ResourceManager.GetString("InvalidMethodBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is {0} running....
        /// </summary>
        internal static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource manager is not set..
        /// </summary>
        internal static string ResourceManagerIsNotSet {
            get {
                return ResourceManager.GetString("ResourceManagerIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0}....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Docker....
        /// </summary>
        internal static string StartingDockerEllipsis {
            get {
                return ResourceManager.GetString("StartingDockerEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup configuration is null..
        /// </summary>
        internal static string StartupConfigurationIsNull {
            get {
                return ResourceManager.GetString("StartupConfigurationIsNull", resourceCulture);
            }
        }
    }
}
